_wandb:
    value:
        cli_version: 0.22.3
        e:
            eo04efs0u6z6ewq69cul7me9n05btxw2:
                args:
                    - --dataset
                    - anatomy
                    - --epoch
                    - "30"
                    - --update_term
                    - "5"
                codePath: stableprompt_qa.py
                codePathLocal: stableprompt_qa.py
                cpu_count: 16
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "66859720704"
                email: c3332019@outlook.com
                executable: /opt/conda/bin/python
                git:
                    commit: 9b873b69e1dd04e969555b83fd8a55e2ad8bdda4
                gpu: NVIDIA GeForce RTX 5070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      memoryTotal: "8546942976"
                      name: NVIDIA GeForce RTX 5070 Laptop GPU
                      uuid: GPU-48dc6da8-46de-8beb-e985-3133c9fff370
                host: 4c3e0eab7697
                memory:
                    total: "16502673408"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /workspace/stableprompt_qa.py
                python: CPython 3.11.14
                root: /workspace
                startedAt: "2025-11-14T03:53:39.619044Z"
                writerId: eo04efs0u6z6ewq69cul7me9n05btxw2
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 84
                - 98
                - 100
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 84
                - 98
                - 100
            "3":
                - 13
                - 16
                - 24
            "4": 3.11.14
            "5": 0.22.3
            "6": 4.57.1
            "12": 0.22.3
            "13": linux-x86_64
agent_model:
    value: Qwen/Qwen3-0.6B
batch_size:
    value: 4
cache_dir:
    value: /mnt/sdb/llm/
dataset:
    value: anatomy
epochs:
    value: 30
max_prompt_length:
    value: 50
meta_prompt:
    value: "I gave a friend an instruction and three inputs. \n                        The friend read the instruction and wrote an output for every one of the inputs.\n                        Here are the input-output pairs: \n"
num_example:
    value: 3
num_test_example:
    value: 20
prompt_per_example:
    value: 3
target_model:
    value: Qwen/Qwen3-0.6B-Base
task:
    value: qa
train_data_per_labels:
    value: 10
trl_ppo_trainer_config:
    value:
        adap_kl_ctrl: true
        backward_batch_size: 3
        batch_size: 3
        cliprange: 0.2
        cliprange_value: 0.2
        compare_steps: 1
        dataset_num_proc: null
        early_stopping: false
        exp_name: stableprompt_qa
        forward_batch_size: null
        gamma: 1
        global_backward_batch_size: 3
        global_batch_size: 3
        gradient_accumulation_steps: 1
        gradient_checkpointing: false
        horizon: 10000
        init_kl_coef: 0.2
        is_encoder_decoder: false
        is_peft_model: true
        kl_penalty: kl
        lam: 0.95
        learning_rate: 1e-05
        log_with: wandb
        max_grad_norm: null
        mini_batch_size: 3
        model_name: Qwen/Qwen3-0.6B
        optimize_cuda_cache: null
        optimize_device_cache: false
        ppo_epochs: 4
        query_dataset: imdb
        ratio_threshold: 10
        remove_unused_columns: true
        reward_model: sentiment-analysis:lvwerra/distilbert-imdb
        score_clip: null
        seed: 0
        steps: 20000
        target: 6
        target_kl: 1
        task_name: null
        total_ppo_epochs: 6667
        tracker_project_name: trl
        use_score_norm: false
        use_score_scaling: false
        vf_coef: 0.1
        whiten_rewards: false
        world_size: 1
update_term:
    value: 5
update_threshold:
    value: 0.05
verbalizer:
    value: null
